source "https://rubygems.org"

gem "jekyll", "~> 3.10"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "just-the-docs", "~> 0.10"

# Required by GitHub Pages
gem "github-pages", group: :jekyll_plugins
